# 由 model-catalog.json 的 legacyPriceKeys 投影旧 prices.json（旧客户端兼容）。
# 用法：./tools/export-legacy-prices.ps1
$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
$Catalog = Join-Path $Root 'model-catalog.json'
$Out = Join-Path $Root 'prices.json'
$py = @'
import json, sys
from pathlib import Path
catalog = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
prices = []
seen = {}
for m in catalog.get("models", []):
    price = m.get("price")
    if not price:
        continue
    for key in m.get("legacyPriceKeys") or []:
        k = key.strip()
        if not k:
            continue
        if k in seen and seen[k] != m.get("modelId"):
            raise SystemExit(f"legacy key {k} maps to {seen[k]} and {m.get('modelId')}")
        seen[k] = m.get("modelId")
        row = {
            "model": k,
            "inputPer1m": price.get("inputPer1m"),
            "outputPer1m": price.get("outputPer1m"),
            "currency": price.get("currency"),
        }
        if price.get("cacheReadPer1m") is not None:
            row["cacheReadPer1m"] = price.get("cacheReadPer1m")
        if price.get("cacheWritePer1m") is not None:
            row["cacheWritePer1m"] = price.get("cacheWritePer1m")
        prices.append(row)
out = {
    "updatedAt": catalog.get("updatedAt", ""),
    "note": catalog.get("note", "") + " | generated by tools/export-legacy-prices.ps1",
    "prices": prices,
}
Path(sys.argv[2]).write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {len(prices)} legacy price rows")
'@
$tmp = Join-Path $env:TEMP 'export-legacy-prices.py'
Set-Content -Path $tmp -Value $py -Encoding UTF8
# 不写死本机路径：优先 PATH 上的 python，退回 py 启动器（PS 5.1 无 ?. 运算符）
$pythonCmd = Get-Command python -ErrorAction SilentlyContinue
if (-not $pythonCmd) { $pythonCmd = Get-Command py -ErrorAction SilentlyContinue }
if (-not $pythonCmd) { Write-Error '未找到 Python（python 或 py 启动器），无法生成旧格式 prices.json'; exit 1 }
& $pythonCmd.Source $tmp $Catalog $Out
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
